### ISSUE TITLE
when IPv6 disabled

### ISSUE THREAD

**Issue by dlyserg** [jkfran/killport#10]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound(Some("/proc/net/tcp6"))', src/linux.rs:42:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

**Comment by jkfran** [comment]
Please install the latest version. v0.8.0
