### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by axetroy** [jkfran/killport#12]
We can find the process via `netstat.exe -ano` and kill with via `taskkill.exe /F /T /PID {processID}` in windows

Here is the example code

Find process:
https://github.com/axetroy/kpv/blob/master/process/find_by_port_windows.c.v

Kill process:
https://github.com/axetroy/kpv/blob/master/process/kill_windows.c.v

**Comment by BasixKOR** [comment]
The WinAPI equivalents are: [`GetTcpTable2`](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getextendedtcptable)'s `dwOwningPid`, [`TerminateProcess`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess?redirectedfrom=MSDN).

Can I try implementing this?
