### ISSUE TITLE
Why not bash? 

### ISSUE THREAD

**Issue by webgtx** [jkfran/killport#16]
**No offense**, just curious why not. You literally need 3 pipes in shell with commands like:
- netstat
- grep
- kill/pkill

**Comment by gorshunovr** [comment]
One is enough: `lsof -t -i:8080 | xargs kill -9`

**Comment by jkfran** [comment]
I appreciate the feedback. I know for some people this tool might look unnecessary. But I think anyone doing this operation on a daily basis sees value in it.

The purpose of killport is to provide a simple, cross-platform, and user-friendly alternative. By wrapping the functionality into a single command, killport aims to make the process quicker and easier for users who may not be as familiar with shell commands or prefer a more streamlined approach.

Killport is built with Rust and doesn't need extra dependencies. It can be particularly useful in minimalistic environments like tiny containers or embedded systems, where every bit of storage and resource usage matters and having a lightweight, single-purpose utility can be more efficient than installing multiple tools.

But as I said before, it's up to the people to use it or not. I'm always open to suggestions for improvement. Closing the issue for now.
