### ISSUE TITLE
A mode that just prints out what's listening?

### ISSUE THREAD

**Issue by samwho** [jkfran/killport#26]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice to be able to just print what process is listening to a port.

**Describe alternatives you've considered**

I was considering writing a tool to do this myself, and was looking to see if anyone had built it. This is the closest thing I've found.

**Additional context**

If this feature request is something you're not going to do, would you mind if I created a tool to do this and used some of the code from this repo? 🙏

**Comment by NachiketNamjoshi** [comment]
Any reason for not using something like `netstat` for this purpose? It would be great if you could explain your workflow if you don't mind!

**Comment by samwho** [comment]
I forget the incantation. I just want to run something like `whatslistening 3000`. I could alias it, but it'd be nice to be able to get nicely formatted and detailed information about the process.

**Comment by jkfran** [comment]
I think we should implement something like `--dry-run`. So `killport --dry-run 8080` could report the PID listening on port 8080 and some extra info.

**Comment by samwho** [comment]
I like that a lot.

**Comment by gochannel** [comment]
Has it been implemented now?

**Comment by dotsad** [comment]
`killport --dry-run 8080` is this coming? Thanks.

**Comment by jkfran** [comment]
Yes, it will be on v1. Should be ready in the next weeks

**Comment by jkfran** [comment]
Added on v1. Update killport to v1 to have `--dry-run`
