### ISSUE TITLE
Make v1 available on Window

### ISSUE THREAD

**Issue by jkfran** [jkfran/killport#37]
Perform needed changes on windows.rs to release v1 on it.

Update release action:
https://github.com/jkfran/killport/blob/4997258c1f75825593ed640ca6d71a9852b5125d/.github/workflows/release.yml#L67

**Comment by masoncfrancis** [comment]
Literally came here to make this issue. Would love to have v1 available for windows

**Comment by jkfran** [comment]
Last contributor to help with the Windows release was @jacobtread. I really hope he can have a look into the changes made to release a v1 for Windows. 🙏🏼

**Comment by jacobtread** [comment]
Happy to give it a look tomorrow at around 6pm NZST needed something to write so ill get onto it

**Comment by jacobtread** [comment]
Had a chance to give it some work tonight, draft PR is at #38 got it working and all. Just want to put some polish and final touches on it tomorrow and should be good to go

Only made slight modifications to the mac and linux version (Had to untangle some of the unix specific code thats made it's way into the platform neutral files)
