### ISSUE TITLE
Stop docker containers

### ISSUE THREAD

**Issue by jkfran** [jkfran/killport#6]

**Comment by llagerlof** [comment]
Nice idea. If a docker container opened the desired port, shutdown the container _gracefully_.

**Comment by 0kate** [comment]
@jkfran 
I have implemented stopping docker containers on linux! Could you confirm the PR below? 🙏
https://github.com/jkfran/killport/pull/18

**Comment by jkfran** [comment]
Killport v1 can now kill containers on Linux and Macos. Thank you @0kate for contributing.
