### ISSUE TITLE
Support different signals than SIGKILL

### ISSUE THREAD

**Issue by hiddewie** [jkfran/killport#8]
The `kill` command supports the command-line option to specify the signal sent to the killed processes.

https://www.man7.org/linux/man-pages/man1/kill.1.html, the option `--signal`. 

Sending other signals than SIGKILL can be useful to reload the process listening on a certain port (like nginx), or gracefully shutdown a service, or invoke other user-defined functionality.

Relevant code: https://github.com/jkfran/killport/blob/3a43d037c08ab3aec730dbb66cb6642b873296b2/src/linux.rs#L176

**Comment by NachiketNamjoshi** [comment]
I can pick this up. @jkfran lmk if you have any issues/ideas on this.

**Comment by jkfran** [comment]
@NachiketNamjoshi, Thank you so much! My only suggestion is to keep using [clap](https://docs.rs/clap/latest/clap/) to parse this new argument. Apart from that, you are welcome to be creative 😄

**Comment by 0kate** [comment]
@jkfran I have added some changes for additional options to specify different signal types! (SIGTERM and SIGKILL only now)
I would appreciate it if you could check a PR below 🙏
https://github.com/jkfran/killport/pull/13

**Comment by 0kate** [comment]
@jkfran 
Thank you review and merging PR above! Could I continue to add support for other signal types?

**Comment by jkfran** [comment]
> @jkfran Thank you review and merging PR above! Could I continue to add support for other signal types?

I think Sigterm and Sigkill are enough for killport. Let's see if we get requests about supporting the other signals. Feel free to contribute to any of the [other issues](https://github.com/jkfran/killport/issues).

**Comment by jkfran** [comment]
This issue was solved on https://github.com/jkfran/killport/pull/13

Killport will now use sigterm by default and it is possible to use sigkill by using `-s` or `--signal`.

Thank you so much @0kate for contributing to this project.
